### ISSUE TITLE
Add Circle Ci tests

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/slate-tools#53]
### Problem

We don't have circle ci tests set up for this repo - which would be super handy 👐 

Recent thing issue that happened: Failed to address all the issues from `npm run test` before making a release.  NPM stopped us from publishing (which is great), but had to delete the recent release and do some quick-fix branches.

### Scope

Tests to run:
* All our our es-lint stuff
* Not convinced at this point we should have a requirement that a reviewer ✅ the PR because this will prevent quick solo fixes.

**Comment by chrisberthe** [comment]
I'm up for keeping the approval requirement. Do we really want to quick solo fix?
