### ISSUE TITLE
Deploying changes rather than watching them will reset the settings/config in a store

### ISSUE THREAD

**Issue by adrhumphreys** [Shopify/slate-tools#54]
### Problem

When you have a setting that has been changed (e.g. the logo), upon build/deploy of a theme then the setting will not be set.

It appears to not take the default value either and will just have a null value

### Replication steps

I've added a setting to settings_schema.json
```
{
  "type": "html",
  "id": "header_text",
  "label": "Text",
  "default": "$5 Flat rate shipping. Sorry, but we can’t ship to countries outside of New Zealand yet. If you have any questions about this <a href=\"/\">contact us</a>."
}
```
When I build then deploy the theme then the text saved in the setting is set to null/empty string. Doesn't use default and doesn't keep what was previously there.

**Comment by t-kelly** [comment]
Hey @adrhumphreys -- this is simular to https://github.com/Shopify/slate/issues/174, the best thing to do is to ignore `settings_data.json`.
