### ISSUE TITLE
Error summary in build process

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/slate-tools#58]
### Problem

Slate isn't giving a summary of errors after running `slate build`.  

A lot of stuff gets outputted in `slate build`, so inline errors can be easily missed.  Ideally, all issues would be summarized at the end.

![](http://take.ms/c49NG)

### Scope

Error seen after running `slate build`.  
The `gulp-cssimport` is encountering an error and logging it, but this is easily missed.

```bash
[19:55:33] Error in plugin 'gulp-cssimport'
Message:
    Cannot find file 'components/mixins' from '/Users/nathanferguson/code/slatevendor/src/styles/vendor/materialize' (includePaths: )
```

### Replication steps

Create a scss file that uses the `@import` directive to import a partial.  In the screenshot, I'm using Materialize's Sass source which can be found at this site: http://materializecss.com/getting-started.html.  Link to sass source zip: http://materializecss.com/bin/materialize-src-v0.98.2.zip

In the above example, gulp-cssimport says it can't find `components/mixins`.  The line triggering this:

```scss
@import "components/mixins";
```

**Comment by macdonaldr93** [comment]
I'm not sure if this method will work with `gulp-cssimport` but the way we resolved this for node-themekit was by using the two different std i/o streams and then differing the error stream to be output last. Here's the code from `node-themekit`: https://github.com/Shopify/node-themekit/blob/master/lib/command.js#L44-L60
