### ISSUE TITLE
Add source maps to build

### ISSUE THREAD

**Issue by NathanPJF** [Shopify/slate-tools#63]
### Problem

A question was posed in the Slate repo about adding source maps to the build by @kettultim https://github.com/Shopify/slate/issues/150

This has also been brought up internally as good development practice to help with debugging production code.  e.g. Narrative theme's minified JS shipped in production.

### Scope

Look into source map implementation for both JS and CSS.

### More Information

I remember that @tiffanytse recently asked us about source maps.  Tiffany: Any context you can share about how this came up?

In the linked issue, @kettultim said he got a working solution with https://www.npmjs.com/package/gulp-sourcemaps - worth looking into.

**Comment by jonathanmoore** [comment]
I was actually about to open a separate issue regarding minification during the build process.  With the premium theme support, we see very frequent requests to minify the JS files in an effort to boost PageSpeed.

Today I was going to try implementing a local variation of [build-js.js](https://github.com/Shopify/slate-tools/blob/master/src/tasks/build-js.js) that preserves the original JS file in case the merchant or developer needs to modify it, but also creates a new theme.js.min version that is loaded in theme.liquid.

Seeing how Narrative handles the JS files is what prompted the idea to make this happen with our next theme update.

**Comment by tiffanytse** [comment]
I had gotten a question on source maps via the blog - I wanted to clarify. From my understanding right now (maybe I'm wrong) the only way to get sort-of-source-maps is to compile the sass locally and have your compiler insert comments into your CSS - which could then be removed on production compile.

**Comment by t-kelly** [comment]
This issue has been moved to https://github.com/Shopify/slate/issues/231
