### ISSUE TITLE
Using special characters in directory name breaks zip tools

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate-tools#68]
### Problem

I created a theme inside a two-word directory with the theme name such as: "Theme name - XXX [Master]" using the command `slate theme "Theme name - XXX [Master]"` and from what I could tell, it created the theme as normal. But when I then ran `slate zip` it killed the build process after `[12:27:24] Finished 'zip' after` with no built theme and no dist folder. I changed the theme's folder name to simply "theme" and it worked perfectly.

Perhaps there's some undocumented restriction on folder names or perhaps a bug.

**Comment by NathanPJF** [comment]
I'm able to reproduce. Labeling as `bug`

**Comment by t-kelly** [comment]
This issue has been moved to https://github.com/Shopify/slate/issues/233
