### ISSUE TITLE
Special Character (©) In SCSS file breaks compilation

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/slate-tools#70]
### Problem

Within the SCSS document and within comment tags, I used the Copyright symbol (©) and it seemed to break the compiler, this applied to other characters and foreign symbols. I ran the same comment within CodePen's SCSS compiler and Sassmeister and neither reported any errors.

Here is the comment I placed in my document:
```
/*============================================================================
  Site Name | Built with Slate
    © Copyright 2017 Liam Merlyn. All rights reserved.
    You are not permitted to use, edit or duplicate this document.
==============================================================================*/
```

**Comment by NathanPJF** [comment]
This issue is related to the character encoding issue posted here: https://github.com/Shopify/slate/issues/204

Closing this as `@charset "UTF-8"` on the first line of your stylesheet will resolve it.
